apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/otikhomi-tenant/my-app-1/devfile-sample-python-basic@sha256:18a19067de22acdf2850676366e69267dafa7cc7ee51011a296ba3180263eca4
        name: my-python
        resources: {}
status: {}
